BRAND_ALIASES = {
    "겔랑": ["겔랑", "게랑", "Guerlain"],
    "구찌": ["구찌", "Gucci"],
    "끌로에": ["끌로에", "끌로 에", "Chloé", "Chloe"],
    "나르시소 로드리게즈": ["나르시소로드리게즈", "나르시소 로드리게즈", "나르시소", "로드리게즈", "Narciso Rodriguez"],
    "니샤네": ["니샤네", "Nishane"],
    "도르세": ["도르세", "도 르세", "D’ORSAY", "D'ORSAY", "DORSAY"],
    "디올": ["디올", "크리스찬디올", "크리스찬 디올", "Dior", "Christian Dior"],
    "딥티크": ["딥티크", "Diptyque"],
    "랑콤": ["랑콤", "Lancôme", "Lancome"],
    "로라 메르시에": ["로라메르시에", "로라 메르시에", "Laura Mercier"],
    "로에베": ["로에베", "Loewe"],
    "록시땅": ["록시땅", "록시탕", "록 시땅", "L’Occitane", "L'Occitane", "LOccitane", "L’Occitane en Provence"],
    "르 라보": ["르라보", "르 라보", "Le Labo"],
    "메모": ["메모", "Memo", "Memo Paris"],
    "메종 마르지엘라": ["메종마르지엘라", "메종 마르지엘라", "마르지엘라", "Maison Margiela"],
    "메종 프란시스 커정": ["메종프란시스커정", "메종 프란시스 커정", "프란시스 커정", "엠에프케이", "MFK", "Maison Francis Kurkdjian"],
    "멜린앤게츠": ["멜린앤게츠", "말린앤게츠", "멜린 앤 게츠", "Malin+Goetz", "Malin and Goetz", "Malin & Goetz"],
    "미우미우": ["미우미우", "미우 미우", "Miu Miu"],
    "바이레도": ["바이레도", "Byredo"],
    "반클리프 아펠": ["반클리프아펠", "반클리프 아펠", "반클리프앤아펠", "Van Cleef & Arpels", "Van Cleef and Arpels", "VCA"],
    "버버리": ["버버리", "Burberry"],
    "베르사체": ["베르사체", "Versace"],
    "불가리": ["불가리", "벌가리", "Bulgari", "BVLGARI"],
    "비디케이": ["비디케이", "BDK", "BDK Parfums"],
    "산타 마리아 노벨라": ["산타마리아노벨라", "산타 마리아 노벨라", "노벨라", "Santa Maria Novella", "SMN"],
    "샤넬": ["샤넬", "Chanel"],
    "세르주 루텐": ["세르주루텐", "세르주 루텐", "Serge Lutens"],
    "시슬리 코스메틱": ["시슬리", "시슬리코스메틱", "시슬리 코스메틱", "Sisley", "Sisley Paris"],
    "아쿠아 디 파르마": ["아쿠아디파르마", "아쿠아 디 파르마", "Acqua di Parma", "AdP"],
    "에따 리브르 도량쥬": ["에따리브르도랑쥬", "에따 리브르 도량쥬", "에따리브르", "Etat Libre d’Orange", "Etat Libre d'Orange", "ELDO"],
    "에르메스": ["에르메스", "Hermès", "Hermes"],
    "에스티 로더": ["에스티로더", "에스티 로더", "Estee Lauder", "Estée Lauder"],
    "엑스 니힐로": ["엑스니힐로", "엑스 니힐로", "Ex Nihilo"],
    "이니시오 퍼퓸": ["이니시오", "이니시오 퍼퓸", "Initio", "Initio Parfums Prives"],
    "이솝": ["이솝", "Aesop"],
    "입생로랑": ["입생로랑", "입 생로랑", "이브생로랑", "이브 생 로랑", "생로랑", "YSL", "Yves Saint Laurent", "Saint Laurent"],
    "제르조프": ["제르조프", "Xerjoff"],
    "조 말론": ["조말론", "조 말론", "Jo Malone", "Jo Malone London", "JML"],
    "조르지오 아르마니": ["조르지오아르마니", "조르지오 아르마니", "아르마니", "Giorgio Armani", "Armani"],
    "줄리엣 헤즈 어 건": ["줄리엣헤즈어건", "줄리엣 헤즈 어 건", "Juliette Has A Gun", "JHAG"],
    "지방시": ["지방시", "Givenchy"],
    "질 스튜어트": ["질스튜어트", "질 스튜어트", "Jill Stuart"],
    "크리드": ["크리드", "Creed"],
    "킬리안": ["킬리안", "Kilian", "Kilian Paris"],
    "톰 포드": ["톰포드", "톰 포드", "톰포 드", "톰 포 드", "Tom Ford"],
    "티파니앤코": ["티파니앤코", "티파니 앤 코", "티파니", "Tiffany & Co.", "Tiffany and Co.", "Tiffany"],
    "퍼퓸 드 말리": ["퍼퓸드말리", "퍼퓸 드 말리", "말리", "Parfums de Marly", "PDM"],
    "펜할리곤스": ["펜할리곤스", "펜할리곤즈", "Penhaligon’s", "Penhaligon's", "Penhaligons"],
    "프라다": ["프라다", "Prada"],
    "프레데릭 말": ["프레데릭말", "프레데릭 말", "Frederic Malle", "Frédéric Malle"],
}


BRAND_LIST = [
    '겔랑', '구찌', '끌로에', '나르시소 로드리게즈', '니샤네', '도르세', '디올', '딥티크', '랑콤',
    '로라 메르시에', '로에베', '록시땅', '르 라보', '메모', '메종 마르지엘라', '메종 프란시스 커정',
    '멜린앤게츠', '미우미우', '바이레도', '반클리프 아펠', '버버리', '베르사체', '불가리', '비디케이',
    '산타 마리아 노벨라', '샤넬', '세르주 루텐', '시슬리 코스메틱', '아쿠아 디 파르마', '에따 리브르 도량쥬',
    '에르메스', '에스티 로더', '엑스 니힐로', '이니시오 퍼퓸', '이솝', '입생로랑', '제르조프', '조 말론',
    '조르지오 아르마니', '줄리엣 헤즈 어 건', '지방시', '질 스튜어트', '크리드', '킬리안', '톰 포드',
    '티파니앤코', '퍼퓸 드 말리', '펜할리곤스', '프라다', '프레데릭 말'
]

CONC_SYNONYMS = {
    "오 드 퍼퓸": ["오 드 퍼퓸", "오드퍼퓸", "EDP", "eau de parfum"],
    "오 드 뚜왈렛": ["오 드 뚜왈렛", "오드뚜왈렛", "EDT", "eau de toilette"],
    "오 드 꼴로뉴": ["오 드 꼴로뉴", "EDC", "eau de cologne"],
    "파르펭": ["파르펭", "Parfum", "Extrait", "Extrait de Parfum"],
}
